### ISSUE TITLE
User can View Tabs for various features.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/Kiwibot#1]
# Motivation
In order to undergo on our project, we want to be able to view the basic interface for our features that we will implement in the future. We will start by implementing a UI that is simple and intuitive to follow, as well as aesthetically pleasing. 

# Task Implementation
- [ ] Create Git Repos that allows me to start the project
- [ ] Create the proper files to get started with this
- [ ] Since many of the actions are generalized, create a general form for each tab.

# Wireframe
![new mockup 1](https://user-images.githubusercontent.com/26865352/27506659-fe4bc9c0-5871-11e7-92cf-fbecd31e4951.png)
