### ISSUE TITLE
User can login/logout through discord to delegate account credentials to a bot.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#1]
# Motivation
This is going to be the first thing we want to do since all the commands will be credentalized and tapped in through the user's information. We also want to create a safe and secure login system so that we can safely enter information and the like without having the fear of having our account security compromised. Because all information will be tied to the account credentials, this step is essential to getting started, and must be tackled first. A combination of OAUTH, express, discord, and node will be used to make sure that the login/logout system works. Ideally, this will have multiple device support, with multiple users being able to log in and out at the same time, without having data compromised.
 
# Task implementation
- [x] Design bar that tells people to login if they haven't.
- [x] After logging in, tell people they have logged in.
- [x] Create a way to logout.
- [x] Make sure that the logouts are conducted if the windows have closed and if the button was pressed.
- [ ] Make sure this can work for multiple systems logged in and out at once.
- [ ] Make sure that private information cannot be accessed by other malicious parties.
- [ ] Make sure that the ports can accurately tie information to its correct account information.
- [ ] Make sure that the user can view their credentials through a tab which displays their information.
- [ ] Make sure that the ports cannot be cross-accessed by malicious parties.
- [ ] Make sure that the file architecture is good for the development for the rest of the way.
 
#Wireframe
 
![new mockup 1](https://user-images.githubusercontent.com/26865352/27549953-b5092266-5a52-11e7-9d92-82994fbdd39d.png)
