### ISSUE TITLE
User can view statuses of Users.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#12]
# Motivation
We want to be able to see the information of users.

# Task Implementation
- [x]  Re-obtain old code for a new grid box
- [x] Get functions to fetch from the API
- [x] Get event listener for the button click.
- [x] Store query into the dom
- [x] Be able to input a search by ID.
- [x] Be able to search a dropdown by name, searchable. 

# Wireframe

![screenshot_1](https://user-images.githubusercontent.com/26865352/28245259-944874ae-69b7-11e7-8bde-8027be0f02b3.png)
