### ISSUE TITLE
User can bookmark to where they were before.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#14]
# Motivation
We want to be able to for expediency be able to go where we last were without having to click through all the tabs. 

# Task implementation
- [x] Implement hashRouter.
- [x] Make sure it fires events properly.
- [x] Make sure it fires for when you load the page.
- [x] Make sure it persists the logged in state when you refresh the page, if you've logged in already. 
- [x] Make sure that the localhost retains the user token through each load, if it has one.
- [x] Make sure that the hash is hidden after you "log in"
- [x] Make sure that the server choice is retained after you refresh
- [x] When you try to access that bookmarked url and you are not initially logged in, it will direct you to log in.
- [x] When you go back also remember what your last last server was and hop to that. 

# Wireframe

![screen shot 2017-07-19 at 1 56 53 pm](https://user-images.githubusercontent.com/26865352/28389227-27d06928-6c8a-11e7-983b-c5c62c86f291.png)
