### ISSUE TITLE
User will be prevented from accessing servers that kiwibot is not on. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#17]
# Motivation

We don't want people editting on servers that the bot is not on. Therefore we will block the people who try illegal accesses from entering those servers. 

# Task Implementation
- [x] Attach a check to server changes
- [x] Attach Redirect them back to where they were before if they aren't supposed to be on that new server. 
- [ ] Delegate all the server-related variable loading to the switch instead of user choiced buttons.

![kiwibot-demo](https://user-images.githubusercontent.com/26865352/29554227-2f326a8c-86d3-11e7-88f3-e8163f7c3059.gif)
