### ISSUE TITLE
User can apply disciplinary action on users.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/Kiwibot#2]
# Motivation
Now that we have a basic skeletal, we want to go ahead with the first of the generalized actions, to be able to kick/ban users. 

# Task Implementation
- [ ] Be able to fetch information from discord API
- [ ] Be able to select/de-select and clear the list
- [ ] Be able to verify that the fields are all filled appropriately. 
- [ ] Be able to verify that the actions are all logged correctly. 
- [ ] Be able to record who applied the action. 
- [ ] Be able to verify that the action was completed successfully. 

#WireFrame 

![new mockup 1](https://user-images.githubusercontent.com/26865352/27506690-dcce5aa0-5872-11e7-820a-6ad633c1a5f0.png)
