### ISSUE TITLE
User can apply disciplinary action on users.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#3]
# Motivation
Now that we have a basic skeletal, we want to go ahead with the first of the generalized actions, to be able to kick/ban users.
 
# Task Implementation
- [x] Create a dropdown multiple search to search for all users.
- [x] Be able to fetch the list from discord. 
- [x] Create a database to house the strikes, with a unique part of userid to server id.
- [x] Be able to add users. 
- [x] Be able to add/remove strikes to existing users. 
- [ ] Be able to attach a reason to these actions. 
- [x] Verify that the totals and actions are correct. on the table. 
- [ ] Be able to click on a user, and then see how many strikes they have. 
- [ ] Verify that the number displayed matches the table. 

#WireFrame
 
![new mockup 1](https://user-images.githubusercontent.com/26865352/27506690-dcce5aa0-5872-11e7-820a-6ad633c1a5f0.png)
