### ISSUE TITLE
User can view statuses of Users and servers

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/Kiwibot#3]
# Motivation
We want to not only be able to apply actions, but also to see the basic user and server information. 

# Task Implementation
- [ ] Create Fields to implement these things
- [ ] Fetch data from discord's API
- [ ] For each respective tab, be able to view the statuses/settings of the options selected. 

# Wireframe
TBA
