### ISSUE TITLE
User can manage swears

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#5]
# Motivation
We want to be able to robustly manage swears. To be able to add or remove swears, check for key roots, search a swear and find its associated whitelisted words that include that swear (such as s*it and mishit/misshit). We also want to be able to control what rooms are enforced and whether to punish the user for saying the bad words. We also want to be able to see who is exempted from the filter and be able to manage the exempted users.
 
# Task Implementation
- [x] Create a tab called "Manage Swears".
- [x] Be able to view Current Swears.
- [x] Be able to view whitelisted words that are connected to current swears.
- [x] Be able to add/remove swears.
- [x] Be able to add/remove whitelisted words.
- [x] Be able to view the blacklisted words.
 
# Wireframe
![screen shot 2017-07-14 at 10 10 31 am](https://user-images.githubusercontent.com/26865352/28222522-b5d3d3d4-687c-11e7-836f-25a18b8522f3.png)
