### ISSUE TITLE
User can login through discord. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/Kiwibot#5]
# Motivation
This is going to be the first thing we want to do since all the commands will be credentalized and tapped in through the user's information. We also want to create a safe and secure login system so that we can safely enter information and the like without having the fear of having our account security compromised. 

# Task implementation 
- [ ] Design bar that tells people to login if they haven't.
- [ ] After logging in, tell people they have logged in.
- [ ] Create a way to logout.

#Wireframe
![new mockup 1](https://user-images.githubusercontent.com/26865352/27549953-b5092266-5a52-11e7-9d92-82994fbdd39d.png)
