### ISSUE TITLE
Admin-level Users can configure role permissions and access of the web dashboard. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/Kiwibot#6]
# Motivation
We want to be able to control who has admin level access and who gets to see and change what. 

# Task Implementation

- [ ] Create a generic multicheck button interface
- [ ] Implement the following booleans:
- [ ] Administrator
- [ ] View Audit Logs
- [ ] Manage Server
- [ ] Manage Roles
- [ ] Manage Channels
- [ ] Kick Members
- [ ] Ban Members
- [ ] Create Instant Invite
- [ ] Change Nicknames
- [ ] Manage Nicknames
- [ ] Manage Emojis
- [ ] Manage Webbooks
- [ ] Read Messages
- [ ] Send Messages
- [ ] Send TTS Messages
- [ ] Manage Messages
- [ ] Embed Links
- [ ] Embed Links
- [ ] Attach Files
- [ ] Read Message History
- [ ] Mention Everyone
- [ ] Use External Emojis
- [ ] Add Reactions

# Wireframe 

Coming soon
