### ISSUE TITLE
Users can manage channels

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#7]
# Motivation

We want to be able to manage channel settings.
 
# Task Implementation
 
- [ ] Create a tab that says "Manage Channels"
 
Implement following options as 3 part radio buttons:
 
- [ ] Create Instant Invite
- [ ] Manage Channel
- [ ] Manage Permissions
- [ ] Manage Webhooks
- [ ] Read Messages
- [ ] Send Messages
- [ ] Send TTS Messages
- [ ] Manage Messages
- [ ] Embed Links
- [ ] Attach Files
- [ ] Read Message History
- [ ] Mention Everyone
- [ ] Use External Emojis
- [ ] Add Reactions
 
# Wireframe

Coming soon.
