### ISSUE TITLE
Users can manage channels

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/Kiwibot#7]
# Motivation

# Task Implemention

- [ ] Create a tab that says "Manage Channels"

Implement following options as 3 part radio buttons:

- [ ] Create Instant Invite
- [ ] Manage Channel
- [ ] Manage Permissions
- [ ] Manage Webhooks
- [ ] Read Messages
- [ ] Send Messages
- [ ] Send TTS Messages
- [ ] Manage Messages
- [ ] Embed Links
- [ ] Attach Files
- [ ] Read MEssage History
- [ ] Mention Everyone 
- [ ] Use External Emojis
- [ ] Add Reactions

# Wireframe

Coming soon
