### ISSUE TITLE
User can sign up.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/kiwibot#8]
# Motivation
Now that we can enable access to discord to delegate access to a user account, we want to be able to create a secure login where we check upon a session ID, hash passwords and more.
 
# Task implementation
- [ ] Read through victor's readings
- [ ] Create form on the page to listen register.
- [ ] Create a table to store the credentials
- [ ] Create a hasher for the password.
- [ ] Be able to verify that the username isn't already taken by someone else upon submission.
- [ ] When the checking is good, make sure that the data is added to the table.
- [ ] View the table to check if it's there.
- [ ] Make sure that the fields are correct.
- [ ] Give them a login token upon completion.
 
# Wireframe
 
![screen shot 2017-07-11 at 11 10 48 am](https://user-images.githubusercontent.com/26865352/28083268-a982653c-6629-11e7-9738-f6c7ef5a5084.png)
